/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import komunikacija.Komunikacija;
import model.SkriveniBroj;
import model.User;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Acer
 */
public class ClientWorkingForm extends javax.swing.JFrame {
private User ulogovaniUser=null;
private int pokusaja = 5;
private int pogodjenih = 0;
    
    
    
    /**
     * Creates new form ClientWorkingForm
     */
    public ClientWorkingForm(User u) {
        initComponents();
        this.ulogovaniUser=u;
        jLabelWelcome.setText("Dobrodošli, "+ulogovaniUser.getName()+" "+ ulogovaniUser.getSurname());
    }
    public User getUlogovaniUser() {
        return ulogovaniUser;
    }

    public void setUlogovaniUser(User ulogovaniUser) {
        this.ulogovaniUser = ulogovaniUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGame = new javax.swing.JTable();
        jLabelWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableGame.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jTableGame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableGame.setRowHeight(75);
        jTableGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableGame);

        jLabelWelcome.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelWelcome.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGameMouseClicked
        
       // izvuci polje koje je kliknuo korisnik
       JTable tabela = (JTable) evt.getSource();
        Point p = evt.getPoint();
        
        int red = tabela.rowAtPoint(p);
        int kol = tabela.columnAtPoint(p);
        
        if(red!=-1 && kol!=-1){
            
            SkriveniBroj sb = new SkriveniBroj(red, kol, -1);
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.IGRA);
            kz.setParametar(sb);
            Komunikacija.getInstance().posaljiZahtev(kz);
            //......
            ServerskiOdgovor so = Komunikacija.getInstance().prihvatiOdgovor();
            int broj = (int) so.getOdgovor();
            
            tabela.setValueAt(broj, red, kol); // 3, 2,,-1,-1,
              
            
            if(broj!=-1)//1,2, 
                pogodjenih++;
            
            
            if(pogodjenih==3){
                this.dispose();
                JOptionPane.showMessageDialog(null, "Pobedili ste!");
            }
            
            
            pokusaja--;
           if(pokusaja<0 ){
               this.dispose();
               JOptionPane.showMessageDialog(null, "Izgubili ste.");
           }
            
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Morate klikunuti polje tabele!");
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jTableGameMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGame;
    // End of variables declaration//GEN-END:variables
}
